/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-base': '#F5F2EE',
        'bg-base-dark': '#1C1A18',
        'bg-surface': '#FAF8F5',
        'bg-surface-dark': '#1A1816',
        'bg-elevated': '#FAF8F5',
        'bg-elevated-dark': '#1A1816',
        'bg-sidebar': '#F0EDE8',
        'bg-sidebar-dark': '#1A1816',
        'bg-sidebar-active': '#E8E4DE',
        'bg-sidebar-active-dark': '#2A2622',
        'border-primary': 'rgba(0, 0, 0, 0.08)',
        'border-primary-dark': 'rgba(255, 255, 255, 0.08)',
        'border-secondary': 'rgba(0, 0, 0, 0.04)',
        'border-secondary-dark': 'rgba(255, 255, 255, 0.05)',
        'border-focus': 'rgba(0, 0, 0, 0.15)',
        'border-focus-dark': 'rgba(255, 255, 255, 0.2)',
        'text-primary': '#1A1814',
        'text-primary-dark': '#FFFFFF',
        'text-secondary': '#6B6560',
        'text-secondary-dark': '#A39E98',
        'text-tertiary': '#A39E98',
        'text-tertiary-dark': '#8E8E93',
        'text-inverse': '#FFFFFF',
        /* 与 --accent-primary 同步，支持浅色/深色主题切换 */
        brand: {
          500: 'var(--accent-primary)',
          600: 'var(--accent-primary-hover)',
        },
        'accent-primary': '#4A7C6F',
        'accent-primary-dark': '#5FA08F',
        'accent-primary-hover': '#5A9A8C',
        'accent-primary-hover-dark': '#7BB8A8',
        'accent-primary-muted': 'rgba(74, 124, 111, 0.12)',
        'accent-primary-muted-dark': 'rgba(95, 160, 143, 0.15)',
        'accent-secondary': '#8B7355',
        'accent-cyan': '#3A8B8C',
        'status-success': 'var(--status-success)',
        'status-warning': 'var(--status-warning)',
        'status-error': 'var(--status-error)',
        'status-info': 'var(--status-info)',
        'conn-connected': 'var(--connection-connected)',
        'conn-connecting': 'var(--connection-connecting)',
        'conn-disconnected': 'var(--connection-disconnected)',
        'diff-add': '#34C759',
        'diff-remove': '#FF3B30',
        'accent-blue': '#0066FF',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'titlebar': '38px',
        'statusbar': '32px',
      },
      borderRadius: {
        'radius-sm': '2px',
        'radius-md': '6px',
        'radius-lg': '8px',
        'radius-xl': '10px',
        'radius-2xl': '12px',
        'radius-3xl': '16px',
        'radius-full': '9999px',
        xs: "2px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "10px",
        "2xl": "12px",
        "3xl": "16px",
      },
      fontFamily: {
        'inter': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', '"SF Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
      },
      transitionTimingFunction: {
        'mac': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      transitionDuration: {
        fast: '100ms',
        normal: '150ms',
        slow: '250ms',
        'mac': '200ms',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'card': '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
        'floating': '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
        'modal': '0 12px 40px rgba(0, 0, 0, 0.12), 0 4px 12px rgba(0, 0, 0, 0.08)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.08), 0 2px 8px rgba(0, 0, 0, 0.04)',
        'login-btn': '0 4px 12px rgba(74, 124, 111, 0.3)',
        'mac': '0 2px 8px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
        'mac-lg': '0 8px 24px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
        'mac-xl': '0 16px 48px rgba(0, 0, 0, 0.10), 0 4px 12px rgba(0, 0, 0, 0.06)',
        'inner-glow': 'inset 0 1px 2px rgba(255, 255, 255, 0.1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "0.7" },
        },
        "spin": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        'cursor-blink': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'mac-spring': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '70%': { transform: 'scale(1.02)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'mac-slide-up': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'mac-fade': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'mac-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "float": "float 4s ease-in-out infinite",
        "glow-pulse": "glow-pulse 6s ease-in-out infinite",
        "spin": "spin 1s linear infinite",
        "blink": "blink 1s step-end infinite",
        "cursor-blink": "cursor-blink 1s steps(2) infinite",
        "mac-spring": "mac-spring 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "mac-slide-up": "mac-slide-up 0.3s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "mac-fade": "mac-fade 0.2s ease-out forwards",
        "mac-pulse": "mac-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
